'use client';

import React, { useState, useEffect } from 'react';
import { EvidenceRecommendation } from '@/types/seo';
import { Target, Zap, Clock, CheckCircle2, AlertTriangle, ArrowRight, Filter, Info, TrendingUp, Copy, Check, Sparkles, FileCode } from 'lucide-react';
import { SEOExplanationTooltip } from '@/components/SEOExplanationTooltip';
import { AiFixModal } from './AiFixModal';
import { JsonLdSchemaModal } from './JsonLdSchemaModal';
import { Tooltip } from './Tooltip';

interface ActionMatrixRoadmapProps {
  actions: EvidenceRecommendation[];
}

export const ActionMatrixRoadmap: React.FC<ActionMatrixRoadmapProps> = ({ actions }) => {
  const [activeFilter, setActiveFilter] = useState<'ALL' | 'DO_FIRST' | 'PLAN_THIS' | 'DO_NEXT'>('ALL');
  const [copied, setCopied] = useState(false);
  const [selectedActionForAi, setSelectedActionForAi] = useState<EvidenceRecommendation | null>(null);
  const [isSchemaModalOpen, setIsSchemaModalOpen] = useState(false);
  const listContainerRef = React.useRef<HTMLDivElement>(null);

  const handleFilterChange = (filter: 'ALL' | 'DO_FIRST' | 'PLAN_THIS' | 'DO_NEXT') => {
    setActiveFilter(filter);
    if (listContainerRef.current) {
      listContainerRef.current.scrollTop = 0;
    }
  };

  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const raw = localStorage.getItem('analyzeserp_pending_ai_modal');
      if (!raw) return;
      const parsed = JSON.parse(raw);
      if (parsed.type === 'fix' && parsed.issueTitle) {
        if (parsed.timestamp && Date.now() - parsed.timestamp > 15 * 60 * 1000) {
          localStorage.removeItem('analyzeserp_pending_ai_modal');
          return;
        }
        localStorage.removeItem('analyzeserp_pending_ai_modal');

        const matched = actions.find((a) => a.title === parsed.issueTitle);
        if (matched) {
          setSelectedActionForAi(matched);
        } else {
          setSelectedActionForAi({
            id: 'restored-fix-item',
            title: parsed.issueTitle,
            category: parsed.issueCategory || 'General SEO',
            action: parsed.issueDescription || '',
            quadrant: 'DO_FIRST',
            effort: 'LOW',
            evidence: 'SERP consensus audit recommendation',
          } as EvidenceRecommendation);
        }
      }
    } catch (err) {
      console.warn('[ActionMatrixRoadmap] Failed to restore pending AI fix modal:', err);
    }
  }, [actions]);

  const handleCopyChecklist = () => {
    const doFirst = actions.filter((a) => a.quadrant === 'DO_FIRST');
    const planThis = actions.filter((a) => a.quadrant === 'PLAN_THIS');
    const doNext = actions.filter((a) => a.quadrant === 'DO_NEXT');
    const optional = actions.filter((a) => a.quadrant === 'OPTIONAL');

    let md = `# 🎯 SERP Optimization Action Roadmap\n*Generated by AnalyzeSERP (Evidence-Based Checklist)*\n\n`;

    const formatGroup = (title: string, group: EvidenceRecommendation[]) => {
      if (group.length === 0) return '';
      let section = `### ${title}\n`;
      group.forEach((item) => {
        section += `- [ ] **${item.title}** (${item.category} · Effort: ${item.effort})\n`;
        section += `  - **Action:** ${item.action}\n`;
        if (item.businessImpact) {
          section += `  - **Why this matters:** ${item.businessImpact}\n`;
        }
        section += `  - **SERP Evidence:** ${item.evidence}\n`;
      });
      return section + '\n';
    };

    if (doFirst.length > 0) md += formatGroup('🔴 DO FIRST (High Impact · Immediate Wins)', doFirst);
    if (planThis.length > 0) md += formatGroup('🟡 PLAN THIS (High Impact · Strategic Projects)', planThis);
    if (doNext.length > 0) md += formatGroup('🟢 DO NEXT (Medium Impact · Enhancements)', doNext);
    if (optional.length > 0) md += formatGroup('⚪ OPTIONAL (Minor Tuning)', optional);

    navigator.clipboard.writeText(md.trim());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!actions || actions.length === 0) {
    return (
      <div className="glass-panel rounded-3xl p-8 border border-slate-200 dark:border-white/10 text-center space-y-3">
        <CheckCircle2 className="w-10 h-10 text-emerald-500 mx-auto" />
        <h4 className="text-base font-extrabold text-slate-800 dark:text-slate-100">No Major Action Items Detected</h4>
        <p className="text-xs text-slate-500 dark:text-gray-400 max-w-md mx-auto">
          Your page is already well-aligned with ranking competitor content structures.
        </p>
      </div>
    );
  }

  const filteredActions = activeFilter === 'ALL'
    ? actions
    : actions.filter((a) => a.quadrant === activeFilter);

  const doFirstCount = actions.filter((a) => a.quadrant === 'DO_FIRST').length;
  const planThisCount = actions.filter((a) => a.quadrant === 'PLAN_THIS').length;
  const doNextCount = actions.filter((a) => a.quadrant === 'DO_NEXT').length;

  return (
    <div id="action-plan-section" className="glass-panel rounded-3xl p-6 sm:p-8 border border-slate-200 dark:border-white/10 shadow-sm space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-slate-200/80 dark:border-white/10">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 bg-slate-100 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/50">
              Chapter 02 · Prioritized Action Roadmap
            </span>
          </div>
          <h3 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-800 dark:text-slate-100 flex items-center gap-2">
            <Target className="w-5 h-5 text-emerald-500" />
            Impact × Effort Prioritized Action Roadmap
            <SEOExplanationTooltip text="Prioritizes updates by combining estimated SEO ranking impact with execution effort, backed by direct SERP consensus evidence." />
          </h3>
          <p className="text-xs text-slate-500 dark:text-gray-400 mt-1">
            Step-by-step optimization recommendations prioritized by impact and empirical SERP evidence.
          </p>
        </div>

        <Tooltip
          content={copied ? 'Checklist Copied!' : 'Copy Checklist'}
          side="top"
        >
          <button
            type="button"
            onClick={handleCopyChecklist}
            aria-label="Copy as Markdown Checklist"
            className="p-1.5 sm:p-2 rounded-lg text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-100 hover:bg-slate-100 dark:hover:bg-white/10 transition-colors cursor-pointer shrink-0"
          >
            {copied ? (
              <Check className="size-4 text-emerald-500" />
            ) : (
              <Copy className="size-4" />
            )}
          </button>
        </Tooltip>
      </div>

      {/* Segmented Control Filter Tabs */}
      <div className="flex items-center p-1 rounded-xl bg-slate-100 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/50 overflow-x-auto">
        <button
          onClick={() => handleFilterChange('ALL')}
          className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'ALL'
              ? 'bg-white text-slate-800 shadow-xs dark:bg-slate-700 dark:text-slate-100 font-bold'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-100'
          }`}
        >
          All Opportunities ({actions.length})
        </button>

        <button
          onClick={() => handleFilterChange('DO_FIRST')}
          className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'DO_FIRST'
              ? 'bg-white text-slate-800 shadow-xs dark:bg-slate-700 dark:text-slate-100 font-bold'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-100'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-red-500 shrink-0" />
          <span>DO FIRST ({doFirstCount})</span>
        </button>

        <button
          onClick={() => handleFilterChange('PLAN_THIS')}
          className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'PLAN_THIS'
              ? 'bg-white text-slate-800 shadow-xs dark:bg-slate-700 dark:text-slate-100 font-bold'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-100'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-amber-500 shrink-0" />
          <span>PLAN THIS ({planThisCount})</span>
        </button>

        <button
          onClick={() => handleFilterChange('DO_NEXT')}
          className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'DO_NEXT'
              ? 'bg-white text-slate-800 shadow-xs dark:bg-slate-700 dark:text-slate-100 font-bold'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-100'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-emerald-500 shrink-0" />
          <span>DO NEXT ({doNextCount})</span>
        </button>
      </div>

      {/* Action Cards List - Contained In-Card Scroll Viewport */}
      <div
        ref={listContainerRef}
        className="space-y-4 pt-1 max-h-[560px] sm:max-h-[600px] overflow-y-auto modal-scroll pr-1.5 focus:outline-none"
        tabIndex={0}
        aria-label="Prioritized action roadmap items"
      >
        {filteredActions.map((item, idx) => {
          let cardColorClass = 'bg-slate-50/80 dark:bg-slate-800/40 border-slate-200 dark:border-slate-700/60 border-l-slate-400';
          let badgeColorClass = 'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-200 border-slate-200 dark:border-slate-700';
          let impactColorClass = 'text-slate-700 dark:text-slate-300';

          if (item.quadrant === 'DO_FIRST') {
            cardColorClass = 'bg-rose-50/60 dark:bg-rose-950/25 border-rose-200/80 dark:border-rose-900/40 border-l-rose-500';
            badgeColorClass = 'bg-rose-100 text-rose-800 dark:bg-rose-900/60 dark:text-rose-200 border-rose-200/80 dark:border-rose-800/50';
            impactColorClass = 'text-rose-700 dark:text-rose-400 font-bold';
          } else if (item.quadrant === 'PLAN_THIS') {
            cardColorClass = 'bg-amber-50/60 dark:bg-amber-950/25 border-amber-200/80 dark:border-amber-900/40 border-l-amber-500';
            badgeColorClass = 'bg-amber-100 text-amber-800 dark:bg-amber-900/60 dark:text-amber-200 border-amber-200/80 dark:border-amber-800/50';
            impactColorClass = 'text-amber-700 dark:text-amber-400 font-bold';
          } else if (item.quadrant === 'DO_NEXT') {
            cardColorClass = 'bg-emerald-50/60 dark:bg-emerald-950/25 border-emerald-200/80 dark:border-emerald-900/40 border-l-emerald-500';
            badgeColorClass = 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/60 dark:text-emerald-200 border-emerald-200/80 dark:border-emerald-800/50';
            impactColorClass = 'text-emerald-700 dark:text-emerald-400 font-bold';
          }

          return (
            <div
              key={item.id || idx}
              className={`p-4 sm:p-5 rounded-xl border border-l-4 space-y-3.5 transition-all shadow-xs hover:shadow-sm ${cardColorClass}`}
            >
              <div className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className={`px-2.5 py-0.5 rounded text-[10px] font-mono font-bold uppercase tracking-wider border ${badgeColorClass}`}>
                    {item.category}
                  </span>
                  {activeFilter === 'ALL' && (
                    <span className={`text-[10px] font-mono uppercase tracking-wider ${impactColorClass}`}>
                      • {item.quadrant === 'DO_FIRST' ? 'High Impact Quick Win' : item.quadrant === 'PLAN_THIS' ? 'Strategic Milestone' : 'Operational Next'}
                    </span>
                  )}
                </div>

                <div className="text-[11px] font-mono font-semibold text-slate-700 dark:text-slate-300">
                  Effort: <strong className="text-slate-900 dark:text-white uppercase font-bold">{item.effort}</strong>
                </div>
              </div>

              {/* Title & Action Step */}
              <div className="space-y-2">
                <h4 className="text-sm sm:text-base font-bold text-slate-900 dark:text-slate-100">
                  {item.title}
                </h4>
                <div className="p-3 rounded-xl bg-white/90 dark:bg-slate-900/80 border border-slate-200/80 dark:border-white/10 text-xs sm:text-sm text-slate-800 dark:text-slate-200 leading-relaxed shadow-2xs">
                  <span className="font-bold text-slate-900 dark:text-white uppercase font-mono text-[10px] tracking-wider block text-slate-500 dark:text-slate-400 mb-1">
                    Recommended Implementation:
                  </span>
                  {item.action}
                </div>
              </div>

              {/* Plain-English Business Impact Callout */}
              {item.businessImpact && (
                <div className="flex items-start gap-2.5 p-3 rounded-xl bg-emerald-500/[0.04] dark:bg-emerald-950/20 border border-emerald-500/20 text-xs text-slate-800 dark:text-slate-200">
                  <TrendingUp className="size-4 text-emerald-600 dark:text-emerald-400 shrink-0 mt-0.5" />
                  <div className="leading-relaxed">
                    <strong className="font-bold text-emerald-800 dark:text-emerald-300">Expected Ranking Impact:</strong>{' '}
                    <span>{item.businessImpact}</span>
                  </div>
                </div>
              )}

              {/* Empirical SERP Evidence Tag & AI Fix Guide Action */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-3 border-t border-slate-200/60 dark:border-white/10">
                <div className="flex items-center gap-1.5 text-xs text-slate-700 dark:text-slate-300 min-w-0">
                  <Info className="size-3.5 text-slate-400 dark:text-slate-500 shrink-0" />
                  <span className="truncate">
                    <strong className="font-semibold text-slate-900 dark:text-slate-100">SERP Evidence:</strong>{' '}
                    <span className="font-mono text-slate-600 dark:text-slate-300">{item.evidence}</span>
                  </span>
                </div>

                <div className="flex items-center gap-2 self-start sm:self-auto shrink-0">
                  {(item.category === 'SCHEMA' || item.id === 'schema-markup-gap') && (
                    <button
                      type="button"
                      onClick={() => setIsSchemaModalOpen(true)}
                      className="px-2.5 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer shadow-xs active:scale-95"
                    >
                      <FileCode className="size-3.5" />
                      <span>Build Schema</span>
                    </button>
                  )}

                  <button
                    type="button"
                    onClick={() => setSelectedActionForAi(item)}
                    className="px-2.5 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer shadow-xs active:scale-95"
                  >
                    <Sparkles className="size-3.5" />
                    <span>AI Fix Guide</span>
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Task Summary Footer */}
      <div className="pt-3 flex flex-col sm:flex-row sm:items-center justify-between gap-1 text-[11px] font-mono font-medium text-slate-700 dark:text-slate-300 border-t border-slate-200/80 dark:border-white/10">
        <span>Showing {filteredActions.length} prioritized recommendations</span>
        <span className="text-slate-500 dark:text-slate-400">All actions backed by real Page 1 SERP consensus</span>
      </div>

      {selectedActionForAi && (
        <AiFixModal
          isOpen={!!selectedActionForAi}
          onClose={() => setSelectedActionForAi(null)}
          issueTitle={selectedActionForAi.title}
          issueCategory={selectedActionForAi.category}
          issueDescription={`${selectedActionForAi.action}${selectedActionForAi.businessImpact ? ' — ' + selectedActionForAi.businessImpact : ''}`}
        />
      )}

      {/* JSON-LD Schema Modal */}
      {isSchemaModalOpen && (
        <JsonLdSchemaModal
          isOpen={isSchemaModalOpen}
          onClose={() => setIsSchemaModalOpen(false)}
          initialTitle="Structured Data & FAQPage Schema"
          initialDescription="Enhance Google search snippet visibility with valid JSON-LD schema markup."
        />
      )}
    </div>
  );
};
