'use client';

import React, { useState, useEffect } from 'react';
import { EvidenceRecommendation } from '@/types/seo';
import { Target, Zap, Clock, CheckCircle2, AlertTriangle, ArrowRight, Filter, Info, TrendingUp, Copy, Check, Sparkles } from 'lucide-react';
import { SEOExplanationTooltip } from '@/components/SEOExplanationTooltip';
import { AiFixModal } from './AiFixModal';

interface ActionMatrixRoadmapProps {
  actions: EvidenceRecommendation[];
}

export const ActionMatrixRoadmap: React.FC<ActionMatrixRoadmapProps> = ({ actions }) => {
  const [activeFilter, setActiveFilter] = useState<'ALL' | 'DO_FIRST' | 'PLAN_THIS' | 'DO_NEXT'>('ALL');
  const [copied, setCopied] = useState(false);
  const [selectedActionForAi, setSelectedActionForAi] = useState<EvidenceRecommendation | null>(null);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const raw = localStorage.getItem('analyzeserp_pending_ai_modal');
      if (!raw) return;
      const parsed = JSON.parse(raw);
      if (parsed.type === 'fix' && parsed.issueTitle) {
        if (parsed.timestamp && Date.now() - parsed.timestamp > 15 * 60 * 1000) {
          localStorage.removeItem('analyzeserp_pending_ai_modal');
          return;
        }
        localStorage.removeItem('analyzeserp_pending_ai_modal');

        const matched = actions.find((a) => a.title === parsed.issueTitle);
        if (matched) {
          setSelectedActionForAi(matched);
        } else {
          setSelectedActionForAi({
            id: 'restored-fix-item',
            title: parsed.issueTitle,
            category: parsed.issueCategory || 'General SEO',
            action: parsed.issueDescription || '',
            quadrant: 'DO_FIRST',
            effort: 'LOW',
            evidence: 'SERP consensus audit recommendation',
          } as EvidenceRecommendation);
        }
      }
    } catch (err) {
      console.warn('[ActionMatrixRoadmap] Failed to restore pending AI fix modal:', err);
    }
  }, [actions]);

  const handleCopyChecklist = () => {
    const doFirst = actions.filter((a) => a.quadrant === 'DO_FIRST');
    const planThis = actions.filter((a) => a.quadrant === 'PLAN_THIS');
    const doNext = actions.filter((a) => a.quadrant === 'DO_NEXT');
    const optional = actions.filter((a) => a.quadrant === 'OPTIONAL');

    let md = `# 🎯 SERP Optimization Action Roadmap\n*Generated by AnalyzeSERP (Evidence-Based Checklist)*\n\n`;

    const formatGroup = (title: string, group: EvidenceRecommendation[]) => {
      if (group.length === 0) return '';
      let section = `### ${title}\n`;
      group.forEach((item) => {
        section += `- [ ] **${item.title}** (${item.category} · Effort: ${item.effort})\n`;
        section += `  - **Action:** ${item.action}\n`;
        if (item.businessImpact) {
          section += `  - **Why this matters:** ${item.businessImpact}\n`;
        }
        section += `  - **SERP Evidence:** ${item.evidence}\n`;
      });
      return section + '\n';
    };

    if (doFirst.length > 0) md += formatGroup('🔴 DO FIRST (High Impact · Immediate Wins)', doFirst);
    if (planThis.length > 0) md += formatGroup('🟡 PLAN THIS (High Impact · Strategic Projects)', planThis);
    if (doNext.length > 0) md += formatGroup('🟢 DO NEXT (Medium Impact · Enhancements)', doNext);
    if (optional.length > 0) md += formatGroup('⚪ OPTIONAL (Minor Tuning)', optional);

    navigator.clipboard.writeText(md.trim());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!actions || actions.length === 0) {
    return (
      <div className="glass-panel rounded-3xl p-8 border border-slate-200 dark:border-white/10 text-center space-y-3">
        <CheckCircle2 className="w-10 h-10 text-emerald-500 mx-auto" />
        <h4 className="text-base font-extrabold text-slate-800 dark:text-slate-100">No Major Action Items Detected</h4>
        <p className="text-xs text-slate-500 dark:text-gray-400 max-w-md mx-auto">
          Your page is already well-aligned with ranking competitor content structures.
        </p>
      </div>
    );
  }

  const filteredActions = activeFilter === 'ALL'
    ? actions
    : actions.filter((a) => a.quadrant === activeFilter);

  const doFirstCount = actions.filter((a) => a.quadrant === 'DO_FIRST').length;
  const planThisCount = actions.filter((a) => a.quadrant === 'PLAN_THIS').length;
  const doNextCount = actions.filter((a) => a.quadrant === 'DO_NEXT').length;

  return (
    <div id="action-plan-section" className="glass-panel rounded-3xl p-6 sm:p-8 border border-slate-200 dark:border-white/10 shadow-sm space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-slate-200/80 dark:border-white/10">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-[10px] uppercase font-bold tracking-wider text-slate-500 dark:text-gray-400 bg-slate-100 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/50">
              Competitive Opportunities Roadmap
            </span>
          </div>
          <h3 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-800 dark:text-slate-100 flex items-center gap-2">
            <Target className="w-5 h-5 text-emerald-500" />
            Impact × Effort Prioritized Action Roadmap
            <SEOExplanationTooltip text="Prioritizes updates by combining estimated SEO ranking impact with execution effort, backed by direct SERP consensus evidence." />
          </h3>
          <p className="text-xs text-slate-500 dark:text-gray-400 mt-1">
            Step-by-step optimization recommendations prioritized by impact and empirical SERP evidence.
          </p>
        </div>

        <button
          type="button"
          onClick={handleCopyChecklist}
          aria-label="Copy action roadmap as markdown checklist"
          className="px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800/80 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-100 text-xs font-semibold flex items-center gap-2 transition-all border border-slate-200 dark:border-slate-700/60 cursor-pointer shrink-0 active:scale-95 shadow-xs"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-500" />
              <span className="text-emerald-700 dark:text-emerald-400 font-bold">Copied Checklist!</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5 text-slate-500 dark:text-slate-400" />
              <span>Copy as Markdown Checklist</span>
            </>
          )}
        </button>
      </div>

      {/* Segmented Control Filter Tabs */}
      <div className="flex items-center p-1 rounded-xl bg-slate-100 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/50 overflow-x-auto">
        <button
          onClick={() => setActiveFilter('ALL')}
          className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'ALL'
              ? 'bg-white text-slate-800 shadow-xs dark:bg-slate-700 dark:text-slate-100 font-bold'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-100'
          }`}
        >
          All Opportunities ({actions.length})
        </button>

        <button
          onClick={() => setActiveFilter('DO_FIRST')}
          className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'DO_FIRST'
              ? 'bg-white text-slate-800 shadow-xs dark:bg-slate-700 dark:text-slate-100 font-bold'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-100'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-red-500 shrink-0" />
          <span>DO FIRST ({doFirstCount})</span>
        </button>

        <button
          onClick={() => setActiveFilter('PLAN_THIS')}
          className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'PLAN_THIS'
              ? 'bg-white text-slate-800 shadow-xs dark:bg-slate-700 dark:text-slate-100 font-bold'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-100'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-amber-500 shrink-0" />
          <span>PLAN THIS ({planThisCount})</span>
        </button>

        <button
          onClick={() => setActiveFilter('DO_NEXT')}
          className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'DO_NEXT'
              ? 'bg-white text-slate-800 shadow-xs dark:bg-slate-700 dark:text-slate-100 font-bold'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-100'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-emerald-500 shrink-0" />
          <span>DO NEXT ({doNextCount})</span>
        </button>
      </div>

      {/* Action Cards List */}
      <div className="divide-y divide-slate-200/80 dark:divide-slate-800 pt-2">
        {filteredActions.map((item, idx) => {
          return (
            <div
              key={item.id || idx}
              className="py-4 space-y-2.5 first:pt-0 last:pb-0"
            >
              <div className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200/80 dark:border-slate-700/50">
                    {item.category}
                  </span>
                  {activeFilter === 'ALL' && (
                    <span className="text-[10px] font-semibold text-slate-600 dark:text-slate-300">
                      • {item.quadrant === 'DO_FIRST' ? 'High Impact' : item.quadrant === 'PLAN_THIS' ? 'High Impact (Plan)' : 'Medium Impact'}
                    </span>
                  )}
                </div>

                <div className="text-[11px] font-mono font-medium text-slate-600 dark:text-slate-300">
                  Effort: <strong className="text-slate-800 dark:text-gray-200 uppercase">{item.effort}</strong>
                </div>
              </div>

              {/* Title & Action Step */}
              <div className="space-y-1">
                <h4 className="text-sm font-bold text-slate-800 dark:text-slate-100">
                  {item.title}
                </h4>
                <p className="text-xs text-slate-700 dark:text-gray-200 leading-relaxed">
                  <strong className="font-semibold text-slate-800 dark:text-slate-100">Recommended Action:</strong> {item.action}
                </p>
              </div>

              {/* Plain-English Business Impact Callout */}
              {item.businessImpact && (
                <div className="flex items-start gap-2 p-2.5 rounded-xl bg-emerald-500/5 dark:bg-emerald-500/[0.04] border border-emerald-500/20 text-[11px] text-slate-700 dark:text-slate-300">
                  <TrendingUp className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400 shrink-0 mt-0.5" />
                  <span className="leading-relaxed">
                    <strong className="font-semibold text-emerald-700 dark:text-emerald-400">Why this matters:</strong>{' '}
                    {item.businessImpact}
                  </span>
                </div>
              )}

              {/* Empirical SERP Evidence Tag & AI Fix Guide Action */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pt-1 border-t border-slate-100 dark:border-slate-800/60 mt-1">
                <div className="flex items-center gap-1.5 text-[11px] text-slate-600 dark:text-slate-300">
                  <Info className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                  <span>
                    <strong className="font-semibold text-slate-700 dark:text-gray-300">SERP Evidence Proof:</strong>{' '}
                    <span className="font-mono">{item.evidence}</span>
                  </span>
                </div>

                <button
                  type="button"
                  onClick={() => setSelectedActionForAi(item)}
                  className="px-2.5 py-1 rounded-lg bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-700 dark:text-emerald-400 text-[11px] font-bold flex items-center gap-1.5 transition-all cursor-pointer self-start sm:self-auto shrink-0 border border-emerald-500/20 active:scale-95"
                >
                  <Sparkles className="w-3 h-3 text-emerald-500" />
                  <span>AI Fix Guide</span>
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {selectedActionForAi && (
        <AiFixModal
          isOpen={!!selectedActionForAi}
          onClose={() => setSelectedActionForAi(null)}
          issueTitle={selectedActionForAi.title}
          issueCategory={selectedActionForAi.category}
          issueDescription={`${selectedActionForAi.action}${selectedActionForAi.businessImpact ? ' — ' + selectedActionForAi.businessImpact : ''}`}
        />
      )}
    </div>
  );
};
