'use client';

import React, { useState, useEffect } from 'react';
import { EvidenceRecommendation } from '@/types/seo';
import { Target, Zap, Clock, CheckCircle2, AlertTriangle, ArrowRight, Filter, Info, TrendingUp, Copy, Check, Sparkles, FileCode } from 'lucide-react';
import { SEOExplanationTooltip } from '@/components/SEOExplanationTooltip';
import { AiFixModal } from './AiFixModal';
import { JsonLdSchemaModal } from './JsonLdSchemaModal';
import { AiActionRoadmapModal } from './AiActionRoadmapModal';
import { Tooltip } from './Tooltip';

interface ActionMatrixRoadmapProps {
  actions: EvidenceRecommendation[];
  targetUrl?: string;
  targetTitle?: string;
  competitorUrls?: string[];
}

export const ActionMatrixRoadmap: React.FC<ActionMatrixRoadmapProps> = ({
  actions,
  targetUrl = '',
  targetTitle,
  competitorUrls = [],
}) => {
  const [activeFilter, setActiveFilter] = useState<'ALL' | 'DO_FIRST' | 'PLAN_THIS' | 'DO_NEXT'>('ALL');
  const [copied, setCopied] = useState(false);
  const [selectedActionForAi, setSelectedActionForAi] = useState<EvidenceRecommendation | null>(null);
  const [isSchemaModalOpen, setIsSchemaModalOpen] = useState(false);
  const [isSprintModalOpen, setIsSprintModalOpen] = useState(false);
  const listContainerRef = React.useRef<HTMLDivElement>(null);

  const handleFilterChange = (filter: 'ALL' | 'DO_FIRST' | 'PLAN_THIS' | 'DO_NEXT') => {
    setActiveFilter(filter);
    if (listContainerRef.current) {
      listContainerRef.current.scrollTop = 0;
    }
  };

  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const raw = localStorage.getItem('analyzeserp_pending_ai_modal');
      if (!raw) return;
      const parsed = JSON.parse(raw);
      if (parsed.type === 'fix' && parsed.issueTitle) {
        if (parsed.timestamp && Date.now() - parsed.timestamp > 15 * 60 * 1000) {
          localStorage.removeItem('analyzeserp_pending_ai_modal');
          return;
        }
        localStorage.removeItem('analyzeserp_pending_ai_modal');

        const matched = actions.find((a) => a.title === parsed.issueTitle);
        if (matched) {
          setSelectedActionForAi(matched);
        } else {
          setSelectedActionForAi({
            id: 'restored-fix-item',
            title: parsed.issueTitle,
            category: parsed.issueCategory || 'General SEO',
            action: parsed.issueDescription || '',
            quadrant: 'DO_FIRST',
            effort: 'LOW',
            evidence: 'SERP consensus audit recommendation',
          } as EvidenceRecommendation);
        }
      }
    } catch (err) {
      console.warn('[ActionMatrixRoadmap] Failed to restore pending AI fix modal:', err);
    }
  }, [actions]);

  const handleCopyChecklist = () => {
    const doFirst = actions.filter((a) => a.quadrant === 'DO_FIRST');
    const planThis = actions.filter((a) => a.quadrant === 'PLAN_THIS');
    const doNext = actions.filter((a) => a.quadrant === 'DO_NEXT');
    const optional = actions.filter((a) => a.quadrant === 'OPTIONAL');

    let md = `# 🎯 SERP Optimization Action Roadmap\n*Generated by AnalyzeSERP (Evidence-Based Checklist)*\n\n`;

    const formatGroup = (title: string, group: EvidenceRecommendation[]) => {
      if (group.length === 0) return '';
      let section = `### ${title}\n`;
      group.forEach((item) => {
        section += `- [ ] **${item.title}** (${item.category} · Effort: ${item.effort})\n`;
        section += `  - **Action:** ${item.action}\n`;
        if (item.businessImpact) {
          section += `  - **Why this matters:** ${item.businessImpact}\n`;
        }
        section += `  - **SERP Evidence:** ${item.evidence}\n`;
      });
      return section + '\n';
    };

    if (doFirst.length > 0) md += formatGroup('🔴 DO FIRST (High Impact · Immediate Wins)', doFirst);
    if (planThis.length > 0) md += formatGroup('🟡 PLAN THIS (High Impact · Strategic Projects)', planThis);
    if (doNext.length > 0) md += formatGroup('🟢 DO NEXT (Medium Impact · Enhancements)', doNext);
    if (optional.length > 0) md += formatGroup('⚪ OPTIONAL (Minor Tuning)', optional);

    navigator.clipboard.writeText(md.trim());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!actions || actions.length === 0) {
    return (
      <div className="glass-panel rounded-3xl p-8 border border-slate-200 dark:border-white/10 text-center space-y-3">
        <CheckCircle2 className="w-10 h-10 text-emerald-500 mx-auto" />
        <h4 className="text-base font-extrabold text-slate-800 dark:text-slate-100">No Major Action Items Detected</h4>
        <p className="text-xs text-slate-500 dark:text-gray-400 max-w-md mx-auto">
          Your page is already well-aligned with ranking competitor content structures.
        </p>
      </div>
    );
  }

  const filteredActions = activeFilter === 'ALL'
    ? actions
    : actions.filter((a) => a.quadrant === activeFilter);

  const doFirstCount = actions.filter((a) => a.quadrant === 'DO_FIRST').length;
  const planThisCount = actions.filter((a) => a.quadrant === 'PLAN_THIS').length;
  const doNextCount = actions.filter((a) => a.quadrant === 'DO_NEXT').length;

  return (
    <div id="action-plan-section" className="rounded-2xl p-5 sm:p-6 bg-white dark:bg-slate-900/60 border border-slate-200/60 dark:border-white/[0.06] shadow-2xs space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-100 dark:border-white/[0.04]">
        <div>
          <span className="text-[10px] font-mono font-medium uppercase tracking-wider text-slate-500 dark:text-slate-400 block mb-0.5">
            Prioritized Roadmap
          </span>
          <h3 className="text-base sm:text-lg font-bold tracking-tight text-slate-900 dark:text-slate-100 flex items-center gap-2">
            <Target className="size-4 text-emerald-500" />
            <span>Impact × Effort Prioritized Action Roadmap</span>
            <SEOExplanationTooltip text="Prioritizes updates by combining estimated SEO ranking impact with execution effort, backed by direct SERP consensus evidence." />
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Step-by-step optimization recommendations prioritized by impact and empirical SERP evidence.
          </p>
        </div>

        <div className="flex items-center gap-2 self-start sm:self-auto shrink-0">
          <button
            type="button"
            onClick={() => setIsSprintModalOpen(true)}
            className="px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-xs flex items-center gap-1.5 transition-all shadow-2xs cursor-pointer active:scale-98"
          >
            <Sparkles className="size-3.5" />
            <span>AI Sprint Execution Plan</span>
            <span className="text-[10px] font-mono bg-emerald-700/60 px-1 py-0.5 rounded text-emerald-100">1 Credit</span>
          </button>

          <Tooltip
            content={copied ? 'Checklist Copied!' : 'Copy Checklist'}
            side="top"
          >
            <button
              type="button"
              onClick={handleCopyChecklist}
              aria-label="Copy as Markdown Checklist"
              className="p-1.5 sm:p-2 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/5 transition-colors cursor-pointer shrink-0"
            >
              {copied ? (
                <Check className="size-4 text-emerald-500" />
              ) : (
                <Copy className="size-4" />
              )}
            </button>
          </Tooltip>
        </div>
      </div>

      {/* Segmented Control Filter Tabs */}
      <div className="flex items-center p-1 rounded-xl bg-slate-100/90 dark:bg-slate-900/90 border border-slate-200/60 dark:border-white/[0.06] overflow-x-auto scrollbar-none gap-1">
        <button
          onClick={() => handleFilterChange('ALL')}
          className={`px-3 py-1.5 rounded-lg text-xs transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'ALL'
              ? 'bg-white text-slate-900 shadow-2xs dark:bg-slate-800 dark:text-white font-semibold border border-slate-200/50 dark:border-white/[0.06]'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200 font-medium'
          }`}
        >
          All ({actions.length})
        </button>

        <button
          onClick={() => handleFilterChange('DO_FIRST')}
          className={`px-3 py-1.5 rounded-lg text-xs flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'DO_FIRST'
              ? 'bg-white text-slate-900 shadow-2xs dark:bg-slate-800 dark:text-white font-semibold border border-slate-200/50 dark:border-white/[0.06]'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200 font-medium'
          }`}
        >
          <span className="size-1.5 rounded-full bg-rose-500 shrink-0" />
          <span>DO FIRST ({doFirstCount})</span>
        </button>

        <button
          onClick={() => handleFilterChange('PLAN_THIS')}
          className={`px-3 py-1.5 rounded-lg text-xs flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'PLAN_THIS'
              ? 'bg-white text-slate-900 shadow-2xs dark:bg-slate-800 dark:text-white font-semibold border border-slate-200/50 dark:border-white/[0.06]'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200 font-medium'
          }`}
        >
          <span className="size-1.5 rounded-full bg-amber-500 shrink-0" />
          <span>PLAN THIS ({planThisCount})</span>
        </button>

        <button
          onClick={() => handleFilterChange('DO_NEXT')}
          className={`px-3 py-1.5 rounded-lg text-xs flex items-center gap-1.5 transition-all cursor-pointer whitespace-nowrap ${
            activeFilter === 'DO_NEXT'
              ? 'bg-white text-slate-900 shadow-2xs dark:bg-slate-800 dark:text-white font-semibold border border-slate-200/50 dark:border-white/[0.06]'
              : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200 font-medium'
          }`}
        >
          <span className="size-1.5 rounded-full bg-emerald-500 shrink-0" />
          <span>DO NEXT ({doNextCount})</span>
        </button>
      </div>

      {/* Action Cards List - Clean Neutral Cards with Subtle Left Accent Line */}
      <div
        ref={listContainerRef}
        className="space-y-3 pt-1 max-h-[560px] sm:max-h-[600px] overflow-y-auto modal-scroll pr-1 focus:outline-none"
        tabIndex={0}
        aria-label="Prioritized action roadmap items"
      >
        {filteredActions.map((item, idx) => {
          let accentBorderClass = 'border-l-slate-400';
          let indicatorTag = null;

          if (item.quadrant === 'DO_FIRST') {
            accentBorderClass = 'border-l-rose-500';
            indicatorTag = (
              <span className="text-[10px] font-mono font-medium text-rose-600 dark:text-rose-400">
                • Quick Win
              </span>
            );
          } else if (item.quadrant === 'PLAN_THIS') {
            accentBorderClass = 'border-l-amber-500';
            indicatorTag = (
              <span className="text-[10px] font-mono font-medium text-amber-600 dark:text-amber-400">
                • Strategic
              </span>
            );
          } else if (item.quadrant === 'DO_NEXT') {
            accentBorderClass = 'border-l-emerald-500';
            indicatorTag = (
              <span className="text-[10px] font-mono font-medium text-emerald-600 dark:text-emerald-400">
                • Enhancement
              </span>
            );
          }

          return (
            <div
              key={item.id || idx}
              className={`p-4 rounded-xl bg-slate-50/50 dark:bg-white/[0.02] border border-slate-200/50 dark:border-white/[0.05] border-l-2 ${accentBorderClass} space-y-2.5 transition-all hover:bg-slate-50 dark:hover:bg-white/[0.03]`}
            >
              {/* Top Tag Row */}
              <div className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-mono font-medium uppercase tracking-wider text-slate-500 dark:text-slate-400">
                    {item.category}
                  </span>
                  {activeFilter === 'ALL' && indicatorTag}
                </div>

                <div className="text-[11px] font-mono text-slate-500 dark:text-slate-400">
                  Effort: <strong className="text-slate-700 dark:text-slate-300 font-medium">{item.effort}</strong>
                </div>
              </div>

              {/* Title & Action Step - Calm, No Nested Box Inside Box */}
              <div className="space-y-1">
                <h4 className="text-sm font-semibold text-slate-900 dark:text-slate-100">
                  {item.title}
                </h4>
                <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                  {item.action}
                </p>
              </div>

              {/* Plain-English Business Impact Callout */}
              {item.businessImpact && (
                <div className="flex items-start gap-1.5 text-xs text-slate-600 dark:text-slate-300">
                  <TrendingUp className="size-3.5 text-emerald-600 dark:text-emerald-400 shrink-0 mt-0.5" />
                  <p className="leading-relaxed">
                    <strong className="font-semibold text-slate-800 dark:text-slate-200">Expected Impact:</strong>{' '}
                    <span>{item.businessImpact}</span>
                  </p>
                </div>
              )}

              {/* Empirical SERP Evidence Tag & Actions */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pt-2 border-t border-slate-100 dark:border-white/[0.04]">
                <div className="flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400 min-w-0">
                  <Info className="size-3.5 text-slate-400 shrink-0" />
                  <span className="truncate">
                    <span className="font-medium text-slate-700 dark:text-slate-300">Evidence:</span>{' '}
                    <span className="font-mono text-slate-500 dark:text-slate-400">{item.evidence}</span>
                  </span>
                </div>

                {item.category === 'SCHEMA' || item.id === 'schema-markup-gap' ? (
                  <div className="flex items-center gap-2 self-start sm:self-auto shrink-0">
                    <button
                      type="button"
                      onClick={() => setIsSchemaModalOpen(true)}
                      className="px-2.5 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer shadow-2xs active:scale-98"
                    >
                      <FileCode className="size-3.5" />
                      <span>Build Schema</span>
                    </button>
                  </div>
                ) : null}
              </div>
            </div>
          );
        })}
      </div>

      {/* Task Summary Footer */}
      <div className="pt-2 flex flex-col sm:flex-row sm:items-center justify-between gap-1 text-[11px] font-mono text-slate-500 dark:text-slate-400 border-t border-slate-100 dark:border-white/[0.04]">
        <span>Showing {filteredActions.length} prioritized recommendations</span>
        <span>Backed by real Page 1 SERP consensus</span>
      </div>

      {selectedActionForAi && (
        <AiFixModal
          isOpen={!!selectedActionForAi}
          onClose={() => setSelectedActionForAi(null)}
          issueTitle={selectedActionForAi.title}
          issueCategory={selectedActionForAi.category}
          issueDescription={`${selectedActionForAi.action}${selectedActionForAi.businessImpact ? ' — ' + selectedActionForAi.businessImpact : ''}`}
        />
      )}

      {/* JSON-LD Schema Modal */}
      {isSchemaModalOpen && (
        <JsonLdSchemaModal
          isOpen={isSchemaModalOpen}
          onClose={() => setIsSchemaModalOpen(false)}
          initialTitle="Structured Data & Semantic Schema"
          initialDescription="Clarify page semantics and entity relationships for search engines with valid JSON-LD schema markup."
        />
      )}

      {/* 4-Week Strategic AI Sprint Execution Plan Modal */}
      <AiActionRoadmapModal
        isOpen={isSprintModalOpen}
        onClose={() => setIsSprintModalOpen(false)}
        targetUrl={targetUrl}
        targetTitle={targetTitle}
        competitorDomains={competitorUrls.map((u) => {
          try {
            return new URL(u).hostname.replace(/^www\./, '');
          } catch {
            return u;
          }
        })}
        actions={actions.map((a) => ({
          title: a.title,
          category: a.category,
          quadrant: a.quadrant,
          impact: a.businessImpact || a.quadrant,
          effort: a.effort,
          recommendation: a.action,
          evidence: a.evidence,
        }))}
      />
    </div>
  );
};
