import React, { useState } from 'react';
import { SinglePageAudit } from '@/types/seo';
import { analyzeKeywordGaps } from '@/lib/keyword-gap';
import { FileCode, Copy, Download, Check, Sparkles, FileText, Globe, Target } from 'lucide-react';
import jsPDF from 'jspdf';

interface ContentBriefGeneratorProps {
  results: SinglePageAudit[];
}

export const ContentBriefGenerator: React.FC<ContentBriefGeneratorProps> = ({ results }) => {
  const [copied, setCopied] = useState(false);

  const validResults = results.filter((r) => r.status === 'success');
  if (validResults.length === 0) return null;

  // Compute Keyword Gaps for the brief
  const gapAnalysis = analyzeKeywordGaps(validResults);
  const topGaps = gapAnalysis.keywordGaps.slice(0, 10).map((g) => g.phrase);

  // Aggregate word count benchmark & target keyword
  const avgWordCount = Math.round(
    validResults.reduce((acc, r) => acc + r.wordCount, 0) / validResults.length
  );
  const targetWordCount = Math.round(avgWordCount * 1.15); // Recommend 15% longer than average

  // Readability benchmark calculation
  const avgReadabilityEase = Math.round(
    validResults.reduce((acc, r) => acc + (r.readability?.fleschReadingEase || 60), 0) / validResults.length
  );
  const targetGradeLabel = validResults[0]?.readability?.gradeLabel || '8th-9th Grade (Standard)';

  // Extract common top keyword
  const topKw = validResults[0]?.keywords.oneGram[0]?.phrase || 'Target Topic';

  // Aggregate unique H2 and H3 headings across competitors
  const aggregatedHeadings: { level: string; text: string; sourceHost: string }[] = [];
  const seenHeadings = new Set<string>();

  validResults.forEach((r) => {
    let host = 'Competitor';
    try {
      host = new URL(r.url).hostname;
    } catch {
      host = 'Competitor';
    }

    r.headings.forEach((h) => {
      if (h.level === 'h2' || h.level === 'h3') {
        const key = h.text.toLowerCase();
        if (!seenHeadings.has(key)) {
          seenHeadings.add(key);
          aggregatedHeadings.push({
            level: h.level.toUpperCase(),
            text: h.text,
            sourceHost: host,
          });
        }
      }
    });
  });

  // Build Markdown Brief string
  const markdownBrief = `# Content Brief & Outline Template
**Target Keyword / Topic**: ${topKw}
**Recommended Target Word Count**: ${targetWordCount.toLocaleString()} words (Aggregated Benchmark)
**Target Readability Level**: ${targetGradeLabel} (Flesch Ease: ~${avgReadabilityEase}/100)
**Competitor Benchmarks Analyzed**: ${validResults.length} URLs

---

## Recommended Keyword Gaps & Missed Topics to Include
${topGaps.length > 0 ? topGaps.map((g) => `- **${g}**`).join('\n') : '- No major keyword gaps detected.'}

---

## Suggested Content Outline Structure

${aggregatedHeadings
  .map((h) => `${h.level === 'H2' ? '###' : '####'} ${h.text} (Source: ${h.sourceHost})`)
  .join('\n')}

---
*Auto-generated by SEO Competitor Analysis Tool (Non-AI Fast Scraper, Readability & Keyword Gap Engine)*
`;

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownBrief);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdownBrief], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `content-brief-${topKw.replace(/\s+/g, '-')}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('SEO Competitor Content Brief', 14, 20);

    doc.setFontSize(10);
    doc.setFont('Helvetica', 'normal');
    doc.text(`Target Keyword: ${topKw}`, 14, 30);
    doc.text(`Recommended Word Count: ${targetWordCount.toLocaleString()} words`, 14, 36);
    doc.text(`Target Readability: ${targetGradeLabel} (~${avgReadabilityEase}/100 Ease)`, 14, 42);
    doc.text(`Competitors Analyzed: ${validResults.length}`, 14, 48);

    let yPosition = 58;
    if (topGaps.length > 0) {
      doc.setFont('Helvetica', 'bold');
      doc.text('Top Keyword Gaps & Missed Topics:', 14, yPosition);
      yPosition += 6;
      doc.setFont('Helvetica', 'normal');
      doc.text(topGaps.slice(0, 5).join(', '), 14, yPosition);
      yPosition += 10;
    }

    doc.setFont('Helvetica', 'bold');
    doc.text('Suggested Outline Headings:', 14, yPosition);
    yPosition += 8;

    doc.setFont('Helvetica', 'normal');
    aggregatedHeadings.slice(0, 25).forEach((h) => {
      if (yPosition > 280) {
        doc.addPage();
        yPosition = 20;
      }
      const prefix = h.level === 'H2' ? '• [H2] ' : '   - [H3] ';
      doc.text(`${prefix}${h.text} (${h.sourceHost})`, 14, yPosition);
      yPosition += 6;
    });

    doc.save(`content-brief-${topKw.replace(/\s+/g, '-')}.pdf`);
  };

  return (
    <div className="glass-panel rounded-2xl p-6 sm:p-8 border border-slate-200 dark:border-white/10 shadow-xl my-8 space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-[10px] uppercase font-bold tracking-wider bg-purple-500/10 text-purple-700 dark:text-purple-400 border border-purple-500/20">
              High Utility Feature
            </span>
          </div>
          <h3 className="text-xl sm:text-2xl font-black tracking-tight text-slate-900 dark:text-white flex items-center gap-2.5">
            <FileCode className="w-6 h-6 text-purple-600 dark:text-purple-400" />
            1-Click <span className="gradient-text">Content Brief Generator</span>
          </h3>
          <p className="text-xs text-slate-500 dark:text-gray-400 mt-1">
            Aggregates H2/H3 headings, readability benchmarks & keyword gaps into an exportable outline brief.
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleCopyMarkdown}
            className="px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-800 dark:text-gray-200 text-xs font-semibold flex items-center gap-2 transition-all cursor-pointer border border-slate-200 dark:border-white/10 shadow-sm"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600 dark:text-emerald-400" /> : <Copy className="w-4 h-4 text-cyan-600 dark:text-cyan-400" />}
            <span>{copied ? 'Copied Brief!' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="px-3.5 py-2 rounded-xl bg-purple-500/10 hover:bg-purple-500/20 text-purple-700 dark:text-purple-300 text-xs font-semibold flex items-center gap-2 transition-all cursor-pointer border border-purple-500/30 shadow-sm"
          >
            <Download className="w-4 h-4" />
            <span>Download .MD</span>
          </button>

          <button
            onClick={handleDownloadPDF}
            className="px-3.5 py-2 rounded-xl bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-700 dark:text-emerald-300 text-xs font-semibold flex items-center gap-2 transition-all cursor-pointer border border-emerald-500/30 shadow-sm"
          >
            <FileText className="w-4 h-4" />
            <span>Export PDF Brief</span>
          </button>
        </div>
      </div>

      {/* Brief Preview Card */}
      <div className="p-4 sm:p-6 rounded-xl bg-slate-50 dark:bg-[#080c14] border border-slate-200 dark:border-white/10 font-mono text-xs text-slate-800 dark:text-gray-300 space-y-4 max-h-80 overflow-y-auto shadow-inner">
        <div className="text-emerald-700 dark:text-emerald-400 font-bold border-b border-slate-200 dark:border-white/10 pb-2">
          # Target Keyword: {topKw}
          <br />
          <span className="text-slate-500 dark:text-gray-400 font-normal">## Target Word Count: {targetWordCount.toLocaleString()} words</span>
          <br />
          <span className="text-indigo-600 dark:text-indigo-400 font-normal">## Target Readability: {targetGradeLabel} (~{avgReadabilityEase}/100 Ease)</span>
        </div>

        {topGaps.length > 0 && (
          <div className="border-b border-slate-200 dark:border-white/10 pb-2">
            <div className="text-amber-600 dark:text-amber-400 font-bold mb-1">## Recommended Keyword Gaps to Include:</div>
            <div className="text-slate-600 dark:text-gray-400 font-sans text-xs flex flex-wrap gap-1.5">
              {topGaps.map((g, idx) => (
                <span key={idx} className="px-2 py-0.5 rounded bg-amber-500/10 text-amber-700 dark:text-amber-300 border border-amber-500/20 font-mono text-[11px]">
                  {g}
                </span>
              ))}
            </div>
          </div>
        )}

        <div className="space-y-1">
          <div className="text-purple-700 dark:text-purple-400 font-bold mb-2">### Suggested Outline Headings:</div>
          {aggregatedHeadings.map((h, idx) => (
            <div key={idx} className={`py-1 flex items-center justify-between gap-2 ${h.level === 'H2' ? 'text-slate-900 dark:text-white font-semibold pl-2' : 'text-slate-600 dark:text-gray-400 pl-6'}`}>
              <div>
                <span className="text-cyan-600 dark:text-cyan-400">{h.level === 'H2' ? '- H2:' : '  - H3:'}</span> {h.text}
              </div>
              <span className="text-[10px] text-slate-500 dark:text-gray-500 font-sans px-2 py-0.5 rounded bg-slate-200 dark:bg-white/5 border border-slate-300 dark:border-white/5 shrink-0">
                {h.sourceHost}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
