'use client';

import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import {
  Share2,
  Copy,
  Check,
  X,
  Twitter,
  Linkedin,
  Mail,
  MessageSquare,
  ExternalLink,
  Target,
  FileText,
} from 'lucide-react';
import { useFocusTrap } from '@/hooks/useFocusTrap';

interface ShareAuditModalProps {
  isOpen: boolean;
  onClose: () => void;
  targetUrl: string;
  alignmentScore?: number;
  targetKeyword?: string;
  verdictHeadline?: string;
}

export const ShareAuditModal: React.FC<ShareAuditModalProps> = ({
  isOpen,
  onClose,
  targetUrl,
  alignmentScore = 0,
  targetKeyword,
  verdictHeadline,
}) => {
  const modalRef = useFocusTrap<HTMLDivElement>({ isOpen, onClose });
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedSummary, setCopiedSummary] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [canNativeShare, setCanNativeShare] = useState(false);

  useEffect(() => {
    setMounted(true);
    if (typeof navigator !== 'undefined' && !!navigator.share) {
      setCanNativeShare(true);
    }
  }, []);

  if (!isOpen || !mounted) return null;

  const currentUrl = typeof window !== 'undefined' ? window.location.href : targetUrl;
  const host = (() => {
    try {
      return new URL(targetUrl).hostname.replace(/^www\./, '');
    } catch {
      return targetUrl;
    }
  })();

  const shareTitle = `AnalyzeSERP Competitor Benchmark for ${host} (${alignmentScore}% Parity)`;
  const shareText = targetKeyword
    ? `Check out this SERP competitor alignment audit for "${targetKeyword}" on ${host} (${alignmentScore}% SERP Parity Score):`
    : `Check out this competitor benchmark audit for ${host} (${alignmentScore}% SERP Parity Score):`;

  const summaryText = [
    `AnalyzeSERP Competitor Benchmark Report`,
    `--------------------------------------`,
    `Target URL: ${targetUrl}`,
    targetKeyword ? `Target Keyword: "${targetKeyword}"` : '',
    `SERP Parity Score: ${alignmentScore}%`,
    verdictHeadline ? `Verdict: ${verdictHeadline}` : '',
    `Full Interactive Audit: ${currentUrl}`,
  ]
    .filter(Boolean)
    .join('\n');

  const handleCopyLink = () => {
    navigator.clipboard.writeText(currentUrl).then(() => {
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
    });
  };

  const handleCopySummary = () => {
    navigator.clipboard.writeText(summaryText).then(() => {
      setCopiedSummary(true);
      setTimeout(() => setCopiedSummary(false), 2000);
    });
  };

  const handleShareTwitter = () => {
    const tweetText = encodeURIComponent(`${shareText}\n\n${currentUrl}\n#SEO #AnalyzeSERP`);
    window.open(`https://twitter.com/intent/tweet?text=${tweetText}`, '_blank', 'noopener,noreferrer');
  };

  const handleShareLinkedIn = () => {
    window.open(
      `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(currentUrl)}`,
      '_blank',
      'noopener,noreferrer'
    );
  };

  const handleShareWhatsApp = () => {
    const waText = encodeURIComponent(`${shareText}\n\n${currentUrl}`);
    window.open(`https://api.whatsapp.com/send?text=${waText}`, '_blank', 'noopener,noreferrer');
  };

  const handleShareEmail = () => {
    const subject = encodeURIComponent(`SEO Benchmark Audit: ${host} (${alignmentScore}% SERP Parity)`);
    const body = encodeURIComponent(
      `Hi,\n\nHere is the competitive SERP benchmark audit for ${targetUrl}:\n\n` +
        `• SERP Parity Score: ${alignmentScore}%\n` +
        (targetKeyword ? `• Target Keyword: "${targetKeyword}"\n` : '') +
        (verdictHeadline ? `• Verdict: ${verdictHeadline}\n` : '') +
        `\nView the full interactive report here:\n${currentUrl}\n\nGenerated by AnalyzeSERP`
    );
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
  };

  const handleNativeShare = async () => {
    if (typeof navigator !== 'undefined' && navigator.share) {
      try {
        await navigator.share({
          title: shareTitle,
          text: shareText,
          url: currentUrl,
        });
      } catch {
        // User dismissed share dialog or unsupported
      }
    } else {
      handleCopyLink();
    }
  };

  const modalContent = (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="share-modal-title"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-sm animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        ref={modalRef}
        className="relative w-full max-w-lg bg-white dark:bg-slate-900 rounded-2xl p-5 sm:p-6 border border-slate-200/90 dark:border-white/10 shadow-2xl space-y-5 text-slate-800 dark:text-slate-100"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-start justify-between gap-3 pb-3 border-b border-slate-200/80 dark:border-white/[0.08]">
          <div className="space-y-1">
            <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-md text-[10px] font-mono font-bold uppercase tracking-wider bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border border-emerald-500/20">
              <Share2 className="size-3" />
              <span>Shareable Audit Hub</span>
            </div>
            <h3 id="share-modal-title" className="text-base sm:text-lg font-bold text-slate-900 dark:text-slate-100 tracking-tight">
              Share Competitor Benchmark Audit
            </h3>
            <p className="text-xs text-slate-600 dark:text-slate-400 truncate max-w-sm">
              Target: <strong className="text-slate-800 dark:text-slate-200">{host}</strong>
              {targetKeyword && (
                <span>
                  {' '}• Keyword: <strong className="text-slate-800 dark:text-slate-200">"{targetKeyword}"</strong>
                </span>
              )}
            </p>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-500 hover:text-slate-900 dark:hover:text-white border border-slate-200/80 dark:border-white/10 transition-colors cursor-pointer shrink-0"
            aria-label="Close share dialog"
          >
            <X className="size-4" />
          </button>
        </div>

        {/* Section 1: Copy Link Field */}
        <div className="space-y-1.5">
          <label htmlFor="share-direct-url" className="text-xs font-bold text-slate-800 dark:text-slate-200 flex items-center justify-between">
            <span>Direct Audit URL:</span>
            <span className="text-[10px] font-mono text-slate-500 dark:text-slate-400 font-normal">
              1-Click Shareable Link
            </span>
          </label>
          <div className="flex items-center gap-2">
            <input
              id="share-direct-url"
              type="text"
              readOnly
              value={currentUrl}
              onFocus={(e) => e.target.select()}
              className="flex-1 px-3 py-2 rounded-lg text-xs font-mono bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-white/10 text-slate-800 dark:text-slate-200 focus:outline-none focus:border-emerald-500 select-all"
            />
            <button
              type="button"
              onClick={handleCopyLink}
              aria-label="Copy direct audit URL to clipboard"
              className={`px-3 py-2 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all shrink-0 cursor-pointer ${
                copiedLink
                  ? 'bg-emerald-600 text-white font-bold shadow-xs'
                  : 'bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-bold active:scale-95 shadow-xs'
              }`}
            >
              {copiedLink ? (
                <>
                  <Check className="size-3.5" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="size-3.5" />
                  <span>Copy Link</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Section 2: Direct Social & Messaging Channels */}
        <div className="space-y-2">
          <span className="text-[11px] font-mono font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Send Directly To:
          </span>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
            {/* Twitter / X */}
            <button
              type="button"
              onClick={handleShareTwitter}
              className="p-2.5 rounded-xl border border-slate-200/90 dark:border-white/10 bg-slate-50/70 hover:bg-slate-100 dark:bg-white/[0.03] dark:hover:bg-white/[0.08] text-slate-700 dark:text-slate-300 text-xs font-semibold flex items-center justify-center gap-2 transition-all cursor-pointer active:scale-95"
              title="Share on X (Twitter)"
              aria-label="Share on X (Twitter)"
            >
              <Twitter className="size-4 text-sky-500 shrink-0" />
              <span>X (Twitter)</span>
            </button>

            {/* LinkedIn */}
            <button
              type="button"
              onClick={handleShareLinkedIn}
              className="p-2.5 rounded-xl border border-slate-200/90 dark:border-white/10 bg-slate-50/70 hover:bg-slate-100 dark:bg-white/[0.03] dark:hover:bg-white/[0.08] text-slate-700 dark:text-slate-300 text-xs font-semibold flex items-center justify-center gap-2 transition-all cursor-pointer active:scale-95"
              title="Share on LinkedIn"
              aria-label="Share on LinkedIn"
            >
              <Linkedin className="size-4 text-blue-600 dark:text-blue-400 shrink-0" />
              <span>LinkedIn</span>
            </button>

            {/* WhatsApp */}
            <button
              type="button"
              onClick={handleShareWhatsApp}
              className="p-2.5 rounded-xl border border-slate-200/90 dark:border-white/10 bg-slate-50/70 hover:bg-slate-100 dark:bg-white/[0.03] dark:hover:bg-white/[0.08] text-slate-700 dark:text-slate-300 text-xs font-semibold flex items-center justify-center gap-2 transition-all cursor-pointer active:scale-95"
              title="Send via WhatsApp"
              aria-label="Send via WhatsApp"
            >
              <MessageSquare className="size-4 text-emerald-500 shrink-0" />
              <span>WhatsApp</span>
            </button>

            {/* Email */}
            <button
              type="button"
              onClick={handleShareEmail}
              className="p-2.5 rounded-xl border border-slate-200/90 dark:border-white/10 bg-slate-50/70 hover:bg-slate-100 dark:bg-white/[0.03] dark:hover:bg-white/[0.08] text-slate-700 dark:text-slate-300 text-xs font-semibold flex items-center justify-center gap-2 transition-all cursor-pointer active:scale-95"
              title="Send via Email"
              aria-label="Send via Email"
            >
              <Mail className="size-4 text-amber-500 shrink-0" />
              <span>Email</span>
            </button>
          </div>

          {canNativeShare && (
            <button
              type="button"
              onClick={handleNativeShare}
              aria-label="Open system share options"
              className="w-full py-2 px-3 rounded-lg border border-slate-200 dark:border-white/10 bg-slate-100/80 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-700 dark:text-slate-300 text-xs font-medium flex items-center justify-center gap-1.5 transition-colors cursor-pointer"
            >
              <ExternalLink className="size-3.5 text-slate-500" />
              <span>More Sharing Options (System Share)</span>
            </button>
          )}
        </div>

        {/* Section 3: Formatted Summary for Team / Slack / Jira */}
        <div className="space-y-1.5 pt-2 border-t border-slate-200/80 dark:border-white/[0.08]">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-mono font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Formatted Summary (Slack / Jira):
            </span>
            <button
              type="button"
              onClick={handleCopySummary}
              aria-label="Copy formatted audit summary to clipboard"
              className="text-xs font-semibold text-emerald-700 dark:text-emerald-400 hover:underline flex items-center gap-1 cursor-pointer"
            >
              {copiedSummary ? (
                <>
                  <Check className="size-3 text-emerald-500" />
                  <span>Copied Summary!</span>
                </>
              ) : (
                <>
                  <Copy className="size-3" />
                  <span>Copy Summary</span>
                </>
              )}
            </button>
          </div>
          <div className="p-2.5 rounded-lg bg-slate-100 dark:bg-slate-800/60 border border-slate-200/80 dark:border-white/10 text-[11px] font-mono text-slate-700 dark:text-slate-300 leading-relaxed whitespace-pre-wrap select-all">
            {summaryText}
          </div>
        </div>
      </div>
    </div>
  );

  return createPortal(modalContent, document.body);
};
